action_id: trunk-single-player-auto-on-upgrade
date: 2024-03-18 14:37:28
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 07bd01691dee4b65ee8527a3d14cdf45)\x1b[0m\r\n"
  err: ""
timestamp: 1710772648
full_timestamp:
  nanos: 520910000
  seconds: 1710772648
trunk_version: 1.20.1
