action_id: trunk-upgrade-available
date: 2024-03-12 13:09:53
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: ""
timestamp: 1710248993
full_timestamp:
  nanos: 365412000
  seconds: 1710248993
trunk_version: 1.20.1
