action_id: trunk-upgrade-available
date: 2024-03-12 14:14:43
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1710252883
full_timestamp:
  nanos: 390223000
  seconds: 1710252883
trunk_version: 1.20.1
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
