action_id: trunk-upgrade-available
date: 2024-03-12 13:15:50
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: ""
timestamp: 1710249350
full_timestamp:
  nanos: 213848000
  seconds: 1710249350
trunk_version: 1.20.1
