action_id: trunk-upgrade-available
date: 2024-03-12 19:27:14
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: ""
timestamp: 1710271634
full_timestamp:
  nanos: 29189000
  seconds: 1710271634
trunk_version: 1.20.1
