action_id: trunk-share-with-everyone
date: 2024-03-26 18:41:22
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1711478482
full_timestamp:
  nanos: 594088000
  seconds: 1711478482
trunk_version: 1.20.1
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
